import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GlobalUidContext } from "./context/uid";
import { GlobalProjectContext } from "./context/projectId";
import { GlobalSocketContext } from "./context/socket";
import 'bootstrap/dist/css/bootstrap.min.css';

import { LocalizationProvider } from '@mui/x-date-pickers';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ProjeKt",

  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <GlobalSocketContext>
        <GlobalProjectContext>
          <GlobalUidContext>
          
            {children}
          
          </GlobalUidContext>
        </GlobalProjectContext>
        </GlobalSocketContext>
      </body>
    </html>
  );
}
